import { DateIdea, BudgetLevel, EnergyLevel } from '../types';

/**
 * Date Ideas Bank
 *
 * Curated date ideas categorized by:
 * - Budget level
 * - Energy level
 * - Location type
 * - Category/theme
 */

export const dateIdeas: DateIdea[] = [
  // === AT HOME - FREE/BUDGET ===
  {
    id: 'date001',
    title: 'Movie Marathon Night',
    description: 'Pick a theme (80s classics, rom-coms, or a specific director) and watch movies together with homemade snacks.',
    category: 'at_home',
    budgetLevel: 'free',
    energyLevel: 'low',
    duration: 'half_day',
    location: 'at_home',
    tags: ['cozy', 'movies', 'relaxing'],
  },
  {
    id: 'date002',
    title: 'Cook a New Recipe Together',
    description: 'Choose a cuisine neither of you has tried making. Shop for ingredients together and cook as a team.',
    category: 'food',
    budgetLevel: 'budget',
    energyLevel: 'medium',
    duration: 'half_day',
    location: 'at_home',
    tags: ['cooking', 'teamwork', 'food'],
  },
  {
    id: 'date003',
    title: 'Game Night',
    description: 'Board games, card games, or video games. Add some friendly competition with small prizes.',
    category: 'at_home',
    budgetLevel: 'free',
    energyLevel: 'medium',
    duration: 'half_day',
    location: 'at_home',
    tags: ['games', 'fun', 'competitive'],
  },
  {
    id: 'date004',
    title: 'Spa Night at Home',
    description: 'Face masks, candles, relaxing music, and maybe some massage. Pure relaxation together.',
    category: 'relaxation',
    budgetLevel: 'budget',
    energyLevel: 'low',
    duration: 'half_day',
    location: 'at_home',
    tags: ['spa', 'relaxing', 'self-care'],
  },
  {
    id: 'date005',
    title: 'Indoor Picnic',
    description: 'Spread a blanket on the floor, prepare finger foods, and enjoy a picnic without leaving home.',
    category: 'romantic',
    budgetLevel: 'budget',
    energyLevel: 'low',
    duration: 'half_day',
    location: 'at_home',
    tags: ['romantic', 'cozy', 'creative'],
  },
  {
    id: 'date006',
    title: 'Photo Album Creation',
    description: 'Print out your favorite photos together and create a physical photo album of your memories.',
    category: 'at_home',
    budgetLevel: 'budget',
    energyLevel: 'low',
    duration: 'half_day',
    location: 'at_home',
    tags: ['memories', 'creative', 'sentimental'],
  },
  {
    id: 'date007',
    title: 'Breakfast in Bed',
    description: 'Take turns making each other special breakfast and serving it in bed.',
    category: 'romantic',
    budgetLevel: 'budget',
    energyLevel: 'low',
    duration: 'quick',
    location: 'at_home',
    tags: ['romantic', 'morning', 'sweet'],
  },
  {
    id: 'date008',
    title: 'Paint Night',
    description: 'Get some canvases and paint. Follow a YouTube tutorial together or freestyle.',
    category: 'at_home',
    budgetLevel: 'budget',
    energyLevel: 'medium',
    duration: 'half_day',
    location: 'at_home',
    tags: ['creative', 'art', 'fun'],
  },

  // === LOCAL - MODERATE BUDGET ===
  {
    id: 'date009',
    title: 'Farmers Market Visit',
    description: 'Explore a local farmers market, sample foods, and pick up ingredients for a home-cooked meal.',
    category: 'outdoors',
    budgetLevel: 'moderate',
    energyLevel: 'medium',
    duration: 'half_day',
    location: 'local',
    tags: ['outdoor', 'food', 'local'],
  },
  {
    id: 'date010',
    title: 'Coffee Shop Hopping',
    description: 'Visit 3-4 local coffee shops in one day, trying different drinks at each spot.',
    category: 'food',
    budgetLevel: 'moderate',
    energyLevel: 'medium',
    duration: 'half_day',
    location: 'local',
    tags: ['coffee', 'exploration', 'casual'],
  },
  {
    id: 'date011',
    title: 'Museum Day',
    description: 'Explore a local museum together. Art, science, history - pick one that interests you both.',
    category: 'culture',
    budgetLevel: 'moderate',
    energyLevel: 'medium',
    duration: 'half_day',
    location: 'local',
    tags: ['culture', 'educational', 'indoor'],
  },
  {
    id: 'date012',
    title: 'Sunset Picnic',
    description: 'Pack a basket with wine, cheese, and snacks. Find a scenic spot to watch the sunset.',
    category: 'romantic',
    budgetLevel: 'moderate',
    energyLevel: 'low',
    duration: 'half_day',
    location: 'local',
    tags: ['romantic', 'outdoor', 'sunset'],
  },
  {
    id: 'date013',
    title: 'Mini Golf & Ice Cream',
    description: 'Playful competition at mini golf followed by ice cream to celebrate (or console).',
    category: 'adventure',
    budgetLevel: 'moderate',
    energyLevel: 'medium',
    duration: 'half_day',
    location: 'local',
    tags: ['fun', 'games', 'casual'],
  },
  {
    id: 'date014',
    title: 'Bookstore Date',
    description: 'Browse a bookstore together, pick out books for each other, then read at a nearby cafe.',
    category: 'culture',
    budgetLevel: 'moderate',
    energyLevel: 'low',
    duration: 'half_day',
    location: 'local',
    tags: ['books', 'intellectual', 'cozy'],
  },
  {
    id: 'date015',
    title: 'Bike Ride Adventure',
    description: 'Rent bikes and explore a scenic trail or your neighborhood. Stop for snacks along the way.',
    category: 'adventure',
    budgetLevel: 'moderate',
    energyLevel: 'high',
    duration: 'half_day',
    location: 'local',
    tags: ['active', 'outdoor', 'adventure'],
  },
  {
    id: 'date016',
    title: 'Pottery Class',
    description: 'Take a pottery or ceramics class together. Create something to remember the day by.',
    category: 'culture',
    budgetLevel: 'moderate',
    energyLevel: 'medium',
    duration: 'half_day',
    location: 'local',
    tags: ['creative', 'hands-on', 'learning'],
  },

  // === LOCAL - GENEROUS BUDGET ===
  {
    id: 'date017',
    title: 'Fancy Dinner Date',
    description: 'Dress up and visit that restaurant you have been wanting to try. Make it a special occasion.',
    category: 'food',
    budgetLevel: 'generous',
    energyLevel: 'medium',
    duration: 'half_day',
    location: 'local',
    tags: ['romantic', 'food', 'upscale'],
  },
  {
    id: 'date018',
    title: 'Escape Room Challenge',
    description: 'Work together to solve puzzles and escape. Great for teamwork and communication.',
    category: 'adventure',
    budgetLevel: 'generous',
    energyLevel: 'high',
    duration: 'half_day',
    location: 'local',
    tags: ['teamwork', 'puzzles', 'exciting'],
  },
  {
    id: 'date019',
    title: 'Wine or Cocktail Tasting',
    description: 'Visit a local winery or cocktail bar for a tasting experience. Learn something new together.',
    category: 'food',
    budgetLevel: 'generous',
    energyLevel: 'medium',
    duration: 'half_day',
    location: 'local',
    tags: ['drinks', 'sophisticated', 'tasting'],
  },
  {
    id: 'date020',
    title: 'Cooking Class',
    description: 'Take a professional cooking class together. Learn to make pasta, sushi, or pastries.',
    category: 'culture',
    budgetLevel: 'generous',
    energyLevel: 'medium',
    duration: 'half_day',
    location: 'local',
    tags: ['cooking', 'learning', 'hands-on'],
  },
  {
    id: 'date021',
    title: 'Concert or Live Music',
    description: 'See a favorite band or discover new music at a local venue.',
    category: 'culture',
    budgetLevel: 'generous',
    energyLevel: 'high',
    duration: 'half_day',
    location: 'local',
    tags: ['music', 'entertainment', 'exciting'],
  },
  {
    id: 'date022',
    title: 'Comedy Show',
    description: 'Laugh together at a stand-up comedy show or improv night.',
    category: 'culture',
    budgetLevel: 'generous',
    energyLevel: 'medium',
    duration: 'half_day',
    location: 'local',
    tags: ['comedy', 'entertainment', 'fun'],
  },
  {
    id: 'date023',
    title: 'Spa Day',
    description: 'Book a couples massage or spend the day at a spa relaxing together.',
    category: 'relaxation',
    budgetLevel: 'generous',
    energyLevel: 'low',
    duration: 'half_day',
    location: 'local',
    tags: ['relaxing', 'luxury', 'pampering'],
  },
  {
    id: 'date024',
    title: 'Dance Class',
    description: 'Take a salsa, swing, or ballroom dance class. Even if you have two left feet!',
    category: 'adventure',
    budgetLevel: 'generous',
    energyLevel: 'high',
    duration: 'half_day',
    location: 'local',
    tags: ['dancing', 'active', 'romantic'],
  },

  // === OUTDOOR / ADVENTURE ===
  {
    id: 'date025',
    title: 'Hiking Adventure',
    description: 'Find a scenic trail and spend the day hiking. Pack a picnic for the summit.',
    category: 'adventure',
    budgetLevel: 'free',
    energyLevel: 'high',
    duration: 'full_day',
    location: 'local',
    tags: ['hiking', 'nature', 'active'],
  },
  {
    id: 'date026',
    title: 'Beach Day',
    description: 'Sun, sand, swimming. Bring snacks, games, and sunscreen.',
    category: 'outdoors',
    budgetLevel: 'free',
    energyLevel: 'medium',
    duration: 'full_day',
    location: 'local',
    tags: ['beach', 'summer', 'relaxing'],
  },
  {
    id: 'date027',
    title: 'Stargazing Night',
    description: 'Find a dark spot away from city lights. Bring blankets and hot drinks. Look for constellations.',
    category: 'romantic',
    budgetLevel: 'free',
    energyLevel: 'low',
    duration: 'half_day',
    location: 'local',
    tags: ['romantic', 'night', 'peaceful'],
  },
  {
    id: 'date028',
    title: 'Kayaking or Paddleboarding',
    description: 'Rent kayaks or paddleboards and explore a local lake or river.',
    category: 'adventure',
    budgetLevel: 'moderate',
    energyLevel: 'high',
    duration: 'half_day',
    location: 'local',
    tags: ['water', 'active', 'adventure'],
  },
  {
    id: 'date029',
    title: 'Rock Climbing',
    description: 'Try indoor rock climbing together. Encourage and belay each other.',
    category: 'adventure',
    budgetLevel: 'moderate',
    energyLevel: 'high',
    duration: 'half_day',
    location: 'local',
    tags: ['active', 'challenging', 'teamwork'],
  },
  {
    id: 'date030',
    title: 'Camping Trip',
    description: 'Disconnect from technology and reconnect with each other in nature.',
    category: 'adventure',
    budgetLevel: 'moderate',
    energyLevel: 'high',
    duration: 'overnight',
    location: 'travel',
    tags: ['nature', 'adventure', 'overnight'],
  },

  // === SPLURGE / TRAVEL ===
  {
    id: 'date031',
    title: 'Weekend Getaway',
    description: 'Book a nearby Airbnb or hotel for a spontaneous weekend trip.',
    category: 'adventure',
    budgetLevel: 'splurge',
    energyLevel: 'medium',
    duration: 'overnight',
    location: 'travel',
    tags: ['travel', 'adventure', 'romantic'],
  },
  {
    id: 'date032',
    title: 'Hot Air Balloon Ride',
    description: 'Soar above the landscape together. Unforgettable views and romance.',
    category: 'adventure',
    budgetLevel: 'splurge',
    energyLevel: 'medium',
    duration: 'half_day',
    location: 'travel',
    tags: ['adventure', 'romantic', 'unique'],
  },
  {
    id: 'date033',
    title: 'Theme Park Day',
    description: 'Roller coasters, games, and carnival food. Embrace your inner child together.',
    category: 'adventure',
    budgetLevel: 'splurge',
    energyLevel: 'high',
    duration: 'full_day',
    location: 'travel',
    tags: ['fun', 'exciting', 'adventure'],
  },
  {
    id: 'date034',
    title: 'Road Trip',
    description: 'Pick a destination, make a playlist, and hit the road. The journey is the adventure.',
    category: 'adventure',
    budgetLevel: 'splurge',
    energyLevel: 'medium',
    duration: 'full_day',
    location: 'travel',
    tags: ['travel', 'adventure', 'spontaneous'],
  },
  {
    id: 'date035',
    title: 'Luxury Hotel Staycation',
    description: 'Book a nice hotel in your own city. Room service, pool, spa - vacation at home.',
    category: 'relaxation',
    budgetLevel: 'splurge',
    energyLevel: 'low',
    duration: 'overnight',
    location: 'local',
    tags: ['luxury', 'relaxing', 'romantic'],
  },

  // === SURPRISE / UNIQUE ===
  {
    id: 'date036',
    title: 'Recreate Your First Date',
    description: 'Go back to where you had your first date. Recreate the magic.',
    category: 'romantic',
    budgetLevel: 'moderate',
    energyLevel: 'medium',
    duration: 'half_day',
    location: 'local',
    tags: ['nostalgic', 'romantic', 'meaningful'],
  },
  {
    id: 'date037',
    title: 'Scavenger Hunt',
    description: 'Create a scavenger hunt for your partner with clues leading to meaningful spots.',
    category: 'surprise',
    budgetLevel: 'budget',
    energyLevel: 'medium',
    duration: 'half_day',
    location: 'local',
    tags: ['creative', 'fun', 'personalized'],
  },
  {
    id: 'date038',
    title: 'Random Acts of Kindness Day',
    description: 'Spend the day doing good deeds together. Pay for someone\'s coffee, leave kind notes.',
    category: 'adventure',
    budgetLevel: 'moderate',
    energyLevel: 'medium',
    duration: 'full_day',
    location: 'local',
    tags: ['meaningful', 'kindness', 'bonding'],
  },
  {
    id: 'date039',
    title: 'Learn Something New Together',
    description: 'Take a class in something neither of you knows - woodworking, guitar, coding.',
    category: 'culture',
    budgetLevel: 'moderate',
    energyLevel: 'medium',
    duration: 'half_day',
    location: 'local',
    tags: ['learning', 'growth', 'new experiences'],
  },
  {
    id: 'date040',
    title: 'Photo Walk',
    description: 'Walk through a scenic area together, taking photos of each other and the surroundings.',
    category: 'outdoors',
    budgetLevel: 'free',
    energyLevel: 'medium',
    duration: 'half_day',
    location: 'local',
    tags: ['photography', 'outdoor', 'creative'],
  },
];

// Get date ideas by budget
export const getDatesByBudget = (budget: BudgetLevel): DateIdea[] => {
  return dateIdeas.filter((d) => d.budgetLevel === budget);
};

// Get date ideas by energy level
export const getDatesByEnergy = (energy: EnergyLevel): DateIdea[] => {
  return dateIdeas.filter((d) => d.energyLevel === energy);
};

// Get date ideas by category
export const getDatesByCategory = (category: string): DateIdea[] => {
  return dateIdeas.filter((d) => d.category === category);
};

export default dateIdeas;
